# Generated by Django 5.1.6 on 2025-03-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landrequest',
            name='receipt_number',
        ),
    ]
