# Generated by Django 5.1.6 on 2025-03-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_landrequest_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrequest',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
