# Generated by Django 5.1.6 on 2025-03-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_landrequest_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrequest',
            name='comp_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landrequest',
            name='currently_with',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landrequest',
            name='due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landrequest',
            name='file_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landrequest',
            name='sent_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landrequest',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
