# Generated by Django 5.1.6 on 2025-03-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_landrequest_comp_no_landrequest_currently_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrequest',
            name='clerk_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
