# Generated by Django 5.1.6 on 2025-03-19 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_landrequest_clerk_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='landapplication',
            name='user',
        ),
        migrations.DeleteModel(
            name='LandRecord',
        ),
        migrations.DeleteModel(
            name='OwnershipTransfer',
        ),
        migrations.RemoveField(
            model_name='landrequest',
            name='clerk_remark',
        ),
        migrations.AddField(
            model_name='landrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('clerk_review', 'Under Clerk Review'), ('superintendent_review', 'Under Superintendent Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=50),
        ),
        migrations.AlterField(
            model_name='landrequest',
            name='currently_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landrequesthistory',
            name='land_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='myapp.landrequest'),
        ),
        migrations.AddField(
            model_name='landrequesthistory',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LandApplication',
        ),
    ]
