# Generated by Django 5.1.7 on 2025-03-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_landrequest_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrequest',
            name='patta',
            field=models.FileField(blank=True, null=True, upload_to='pattas/'),
        ),
        migrations.AlterField(
            model_name='landrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('clerk_review', 'Under Clerk Review'), ('superintendent_review', 'Under Superintendent Review'), ('project_officer_review', 'Under Project Officer Review'), ('mro_review', 'Under Mro (Mandal Revenue Officer) Review'), ('surveyor_review', 'Under Surveyor Review'), ('revenue_inspector_review', 'Under Revenue Inspector Review'), ('vro_review', 'Under Vro (Village Revenue Officer) Review'), ('revenue_dept_officer_review', 'Under Revenue Department Officer Review'), ('joint_collector_review', 'Under Joint Collector Review'), ('district_collector_review', 'Under District Collector Review'), ('ministry_welfare_review', 'Under Ministry Of Welfare Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=50),
        ),
    ]
