# Generated by Django 5.1.7 on 2025-11-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_landrequest_patta_alter_landrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrequest',
            name='ipfs_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
