# Generated by Django 5.1.7 on 2025-11-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_landrequest_ipfs_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrequest',
            name='txn_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
